version: "2"
services:

  schema-registry-ui:
    image: landoop/schema-registry-ui:latest
    container_name: schema-registry-ui
    ports:
    - "8001:8000"
    environment:
      SCHEMAREGISTRY_URL: "http://192.168.99.100:8081"
      PROXY: "true"

  rest-proxy-ui:
    image: landoop/kafka-topics-ui
    container_name: rest-proxy-ui
    ports:
    - "8002:8000"
    environment:
      KAFKA_REST_PROXY_URL: "http://192.168.99.100:8082"
      PROXY: "true"

  kafka-connect-ui:
    image: landoop/kafka-connect-ui
    container_name: kafka-connect-ui
    ports:
    - "8003:8000"
    environment:
      CONNECT_URL: "http://192.168.99.100:8083"
      PROXY: "true"
